version: "3" # docker-compose version
services: # services which our app going to use. (list of containers we want to create)
  mongo: # container name
    image: mongo # On which image container will build
    ports:
      - "27017:27017"

  api-server:
    build: # Use build context to build the image from Dockerfile in the current directory
      context: ./server # Current directory where your Dockerfile is located
    container_name: api-server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: npm run dev # Start the app after building (ensure the start command runs after the build)
    volumes:
      - ./server:/app # Mount current directory to /app inside the container for hot-reloading (optional)
    environment:
      NODE_ENV: production

  client:
    build:
      context: ./client # Build the client from the ./client directory
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api-server # Wait for the API server to be ready
    volumes:
      - ./client:/app # Mount the client code for development
    command: npm start
    environment:
      NODE_ENV: production
